version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--bind", "0.0.0.0" ]

volumes:
  postgres-data:
